### ISSUE TITLE
IDOPS error

### ISSUE THREAD

**Issue by zhibaosuo** [GAMB-GO/IDOPS#1]
Hi,  an error happens when I run IDOPS. The error information:
Error: Failed to open binary auxfiles for /home/shucl/miniconda3/lib/python3.8/site-packages/idops-0.2.2-py3.8.egg/idops/hmm/idops.hmm: use hmmpress first

ERROR      :hmmscan failed - make sure your environment is properly configured

 I have installed hmmscan, I don't understand twhat happens.

**Comment by r-schoeppe** [comment]
Was IDOPS installed using the conda package or via the source from this repository? 
The conda package should already contain the file processed by hmmpress.

However, you can do that manually as well by executing `hmmpress  /home/shucl/miniconda3/lib/python3.8/site-packages/idops-0.2.2-py3.8.egg/idops/hmm/idops.hmm`

Please let me now if that worked.

**Comment by zhibaosuo** [comment]
I tried again, it worked. Thank you.
